
version: "2"
services:
  ewalletbiblio:
    container_name: ewalletbiblio
    restart: always
    build: .
    ports:
      - "8082:8080"
    networks:
      - linkDb
  dbMYewallet:
    image: "mysql"
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ewallet@ewallet.ewallet
      MYSQL_DATABASE: ewallet
      MYSQL_USER: ewallet
      MYSQL_PASSWORD: ewallet
    volumes:
#      - ./workdir/db/init/:/docker-entrypoint-initdb.d/
      - ./workdir/db/data/:/var/lib/mysql/
      - ./ewallet.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - linkDb


networks:
  linkDb:      
